config-sparse:
  modules:
    ai-ox-tethers:
      config:
        oxtethers:
          enabled:
            contents:
              suggested-value: true
          parameters:
            dynamicMaxOxTethers:
              contents:
                suggested-value: 4
            minimumOxTethersPerQuarry:
              contents:
                suggested-value: 1
            thresholdStoneLoad:
              contents:
                suggested-value: 12
          log:
            contents:
              suggested-value:
                enabled: false
                sliderValue: 2
    ucp2-legacy:
      config:
        ai_access:
          enabled:
            contents:
              suggested-value: true
        ai_assaultswitch:
          enabled:
            contents:
              suggested-value: true
        ai_buywood:
          enabled:
            contents:
              suggested-value: true
        ai_defense:
          enabled:
            contents:
              suggested-value: true
        ai_fix_crusader_archers_pitch:
          enabled:
            contents:
              suggested-value: true
        ai_fix_laddermen_with_enclosed_keep:
          enabled:
            contents:
              suggested-value: true
        ai_nosleep:
          enabled:
            contents:
              suggested-value: true
        ai_rebuild:
          enabled:
            contents:
              suggested-value: true
        ai_tethers:
          enabled:
            contents:
              suggested-value: false
        ai_towerengines:
          enabled:
            contents:
              suggested-value: true
        ai_housing:
          build_housing:
            contents:
              suggested-value:
                enabled: true
                sliderValue: 5
          campfire_housing:
            contents:
              suggested-value:
                enabled: true
                sliderValue: 8
          delete_housing:
            enabled:
              contents:
                suggested-value: true
        ai_resources_rebuy:
          flour:
            contents:
              suggested-value:
                enabled: true
                sliderValue: 12
          iron:
            contents:
              suggested-value:
                enabled: true
                sliderValue: 36
          wood:
            contents:
              suggested-value:
                enabled: true
                sliderValue: 36
        ai_demolish:
          ai_demolish_walls:
            enabled:
              contents:
                suggested-value: true
          ai_demolish_trapped:
            enabled:
              contents:
                suggested-value: true
          ai_demolish_eco:
            enabled:
              contents:
                suggested-value: true
        ai_addattack:
          contents:
            suggested-value:
              enabled: true
              choice: relative
              choices:
                absolute:
                  slider: 5
                relative:
                  slider: 1
        ai_attacklimit:
          contents:
            suggested-value:
              enabled: true
              sliderValue: 3000
        ai_attackwave:
          contents:
            suggested-value:
              enabled: true
              sliderValue: 20
        ai_recruitstate_initialtimer:
          contents:
            suggested-value:
              enabled: true
              sliderValue: 0
        fix_apple_orchard_build_size:
          enabled:
            contents:
              suggested-value: true
        o_firecooldown:
          contents:
            suggested-value:
              enabled: false
              sliderValue: 2000
        o_healer:
          enabled:
            contents:
              suggested-value: true
        o_responsivegates:
          enabled:
            contents:
              suggested-value: true
        u_arabwall:
          enabled:
            contents:
              suggested-value: true
        o_fix_map_sending:
          enabled:
            contents:
              suggested-value: true
        o_fix_rapid_deletion_bug:
          enabled:
            contents:
              suggested-value: true
        o_fix_baker_disappear:
          enabled:
            contents:
              suggested-value: true
        o_fix_fletcher_bug:
          enabled:
            contents:
              suggested-value: true
        o_fix_ladderclimb:
          enabled:
            contents:
              suggested-value: true
        o_fix_moat_digging_unit_disappearing:
          enabled:
            contents:
              suggested-value: true
        o_restore_arabian_engineer_speech:
          enabled:
            contents:
              suggested-value: true
        u_fireballistafix:
          enabled:
            contents:
              suggested-value: true
        u_fix_applefarm_blocking:
          enabled:
            contents:
              suggested-value: true
        u_fix_lord_animation_stuck_movement:
          enabled:
            contents:
              suggested-value: true
        u_tanner_fix:
          enabled:
            contents:
              suggested-value: true
        o_increase_path_update_tick_rate:
          enabled:
            contents:
              suggested-value: true
        o_onlyai:
          enabled:
            contents:
              suggested-value: true
        o_override_identity_menu:
          enabled:
            contents:
              suggested-value: true
        o_xtreme:
          enabled:
            contents:
              suggested-value: true
        o_armory_marketplace_weapon_order_fix:
          enabled:
            contents:
              suggested-value: true
        o_fast_placing:
          enabled:
            contents:
              suggested-value: true
        o_default_multiplayer_speed:
          contents:
            suggested-value:
              enabled: true
              sliderValue: 50
        o_engineertent:
          enabled:
            contents:
              suggested-value: true
        o_gamespeed:
          enabled:
            contents:
              suggested-value: true
        o_keys:
          enabled:
            contents:
              suggested-value: false
        o_moatvisibility:
          enabled:
            contents:
              suggested-value: true
    running-units:
      config:
        macemen:
          running:
            general:
              contents:
                suggested-value: true
        slingers:
          running:
            general:
              contents:
                suggested-value: true
        slaves:
          running:
            general:
              contents:
                suggested-value: true
        spearmen:
          running:
            general:
              contents:
                suggested-value: true
    aiSwapper:
      config: {}
    startResources:
      config: {}
  plugins:
    NewBalance-Nevikov:
      config: {}
meta:
  version: 1.0.0
